### ISSUE TITLE
Latencies between microservices

### ISSUE THREAD

**Issue by salehsedghpour** [EricssonResearch/cloud-native-app-simulator#24]
As we discussed, there seems to be a need for adding a feature to support latencies between microservices either using a service mesh or as a feature inside the application itself. We should decide which one do we need.

**Comment by alekodu** [comment]
Is these latencies between microservices or between clusters. For the former, it can be supported at the application level based on stress-ng.

**Comment by alekodu** [comment]
I think this is contained in issue #18

**Comment by salehsedghpour** [comment]
Yes, also there is a possibility in Istio that we can add latency based on our needs!
